#!/usr/bin/env python3

import snoozeLib
import argparse

parser = argparse.ArgumentParser(description='Snooze selected mails in Mail.app')
parser.add_argument('--list', action='store_true', help='List contents of snooze DB')

args = parser.parse_args()
if args.list:
    snoozeLib.displaySnoozeDb()
else:
    snoozeLib.snoozeMails()
