#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
logfile=$HOME/.snooze-apple-mail-unsnooze.log

exit 0

python3 "$DIR/src/tryUnsnooze.py" > "$logfile" 2>&1
ecode=$?

if [ $ecode -ne 0 ]; then
    echo "Unsnoozing failed with exit code $ecode at $(date)" >> "$logfile"
else
    rm -f "$logfile"
fi
